name: build
on:
  push:
  pull_request:

jobs:
  build:
    name: Node.js ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [8, 10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: node environment
        run: |
          node -v
          npm -v
      - run: npm install
      - run: npm test
